// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    partial class BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Backend.Models.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InternshipPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternshipPeriodId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Backend.Models.Entities.InternshipPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PracticePeriodId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationPeriodId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PracticePeriodId");

                    b.ToTable("InternshipPeriods");
                });

            modelBuilder.Entity("Backend.Models.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdministratorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Backend.Models.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Backend.Models.Entities.Contact", b =>
                {
                    b.HasOne("Backend.Models.Entities.InternshipPeriod", null)
                        .WithMany("Contacts")
                        .HasForeignKey("InternshipPeriodId");
                });

            modelBuilder.Entity("Backend.Models.Entities.InternshipPeriod", b =>
                {
                    b.HasOne("Backend.Models.Entities.Period", "ApplicationPeriod")
                        .WithMany()
                        .HasForeignKey("ApplicationPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Entities.Organization", null)
                        .WithMany("InternshipPeriods")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("Backend.Models.Entities.Period", "PracticePeriod")
                        .WithMany()
                        .HasForeignKey("PracticePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationPeriod");

                    b.Navigation("PracticePeriod");
                });

            modelBuilder.Entity("Backend.Models.Entities.InternshipPeriod", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Backend.Models.Entities.Organization", b =>
                {
                    b.Navigation("InternshipPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
